export default class Model {
    constructor(MODEL_NAME: any, Schema: any);
    MODEL_NAME: any;
    Schema: any;
    createIndices: any;
    removeIndices: any;
    indicesExists: any;
    updateSchema: any;
    updateSettings: any;
    createOne: any;
    createMany: any;
    findOne: any;
    findMany: any;
    findById: any;
    findByIds: any;
    findOneBy: any;
    findManyBy: any;
    findOneAndUpdate: any;
    findManyAndUpdate: any;
    updateOne: any;
    updateMany: any;
    updateById: any;
    updateOneBy: any;
    updateManyBy: any;
    updateByQuery: any;
    remove: any;
    removeById: any;
    list: any;
    search: any;
    findByGeoDistance: any;
    findByDateRange: any;
    findByDate: any;
    count: any;
}
